name: PR Close

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Delete branch
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          base_ref=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_ref=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
          git push origin --delete "$head_ref"
          if [ "$merged" = "true" ]; then
            echo "Deleting branch $head_ref"
            
          else
            echo "PR is not merged. Branch will not be deleted."
          fi
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"    
      - name: Merge master back to feature
        run: |
          git fetch --unshallow
          for branch in $(git branch -r --list "origin/feature/*"); do
            branch_name=$(echo $branch | sed 's/origin\///')
            git checkout -B $branch_name $branch  || true
            git pull || true
            if git merge main --no-commit; then
                git commit -m "Merge main into $branch_name" || true
                git push origin $branch_name || true
            else
                git merge --abort
                git reset --hard HEAD
                continue
            fi
          done
