name: Delete Branch

on:
  pull_request
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          # 获取 PR 相关信息
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          base_ref=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_ref=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
          git push origin --delete "$head_ref"

          # 如果 PR 已合并，则删除分支
          if [ "$merged" = "true" ]; then
            echo "Deleting branch $head_ref"
            
          else
            echo "PR is not merged. Branch will not be deleted."
          fi
