name: Delete Branch

on:
  pull_request
    branches:
      - 'feature/**'
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          # 获取 PR 相关信息
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          base_ref=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
          head_ref=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
          git push origin --delete "$head_ref"

