name: Update feature Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"    

      - name: Merge master back to feature
        run: |
          git fetch --unshallow
          git pull
          for branch in $(git branch -r --list "origin/feature/*"); do
            branch_name=$(echo $branch | sed 's/origin\///')
            git fetch --unshallow
            git checkout -B $branch_name $branch
            git pull
            git merge --no-ff master -m "Auto-merge master back to $branch_name"
            git push origin $branch_name
          done



