name: Update feature Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"    

      - name: Merge master back to feature
        run: |
          git fetch --unshallow
          git pull
          process_branch() {
            local branch=$1
            branch_name=$(echo $branch | sed 's/origin\///')
            git checkout -B $branch_name $branch
            git pull
            git merge --no-ff main -m "Auto-merge master back to $branch_name"
            git push origin $branch_name
          }
          
          trap 'process_branch' ERR
          
          for branch in $(git branch -r --list "origin/feature/*"); do
            git pull
            git merge --quit
            git clean -f
            git reset --hard HEAD
            if ! process_branch $branch; then
              continue
            fi
          done



