name: Update feature Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"    

      - name: Merge master back to feature
        run: |
          git fetch --unshallow
          git pull
          if git merge main --no-commit; then
              git commit -m "Merge main into $branch_name"
              git push origin $branch_name
          else
              git merge --abort
              git reset --hard HEAD
              continue
          fi
          done


